project_name: postee
release:
  draft: false
  prerelease: auto
env:
  - GO111MODULE=off
  - CGO_ENABLED=0
  - GOPATH=/home/runner/work/alm-integration/alm-integration
before:
  hooks:
    - make all
builds:
  - id: postee
    dir: src
    main: ./webhooksrv/webhooksrv.go
    binary: postee
    flags: "-gcflags=-trimpath={GOPATH}/src -asmflags=-trimpath={GOPATH}/src"
    goos:
      - darwin
      - linux
    goarch:
      - amd64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - postee
    replacements:
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .FullCommit }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^test'
      - '^release'
dockers:
  - dockerfile: Dockerfile
    image_templates:
      - "docker.io/aquasec/postee:{{ .Version }}"
      - "public.ecr.aws/aquasecurity/postee:{{ .Version }}"
    ids:
      - postee
    build_flag_templates:
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.name={{ .ProjectName }}"
      - "--label=org.label-schema.description=Command line interface for Postee"
      - "--label=org.label-schema.vendor=Aqua Security"
      - "--label=org.label-schema.version={{ .Version }}"
      - "--label=org.label-schema.build-date={{ .Date }}"
      - "--label=org.label-schema.vcs=https://github.com/aquasecurity/postee"
      - "--label=org.label-schema.vcs-ref={{ .FullCommit }}"